services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: workman-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - workman-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  authdb:
    image: postgres:18

  workman.auth:
    image: ${DOCKER_REGISTRY-}workmanauth
    build:
      context: .
      dockerfile: src/WorkMan/WORKMAN.Auth/Dockerfile

networks:
  workman-network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_auth_data:


